version: '2'
services:
  postgres_data:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: sleep 1m

  postgres:
    image: postgres:latest
    volumes_from:
      - postgres_data

  memcached:
    image: memcached
    mem_limit: 1g
    command: memcached -m 1024m

  backend:
    build: .
    container_name: django_graphql_backend
    command: ./docker-entrypoint.sh
    depends_on:
      - postgres
      - memcached
    environment:
      - DOCKER=true
    ports:
      - "localhost:8000:8000"
